common:
  package_path: /home/zg/Documents/gftPackage
  chrome_driver_path: /home/zg/chromedriver
  doc_path: /home/zg/Downloads/selenium
  timeout: 30
  account_passwd:
    fuzhou: ["FZSKF", "Fzskf@1234"]
    lean: ["LAXKF", "Laxkf@123456"]
    guangchang: ['GCXKF', 'Gcxkf@123456']
    yihuang: ['YHXKF', 'Yhxkf@123456']
    linchuan: ['LCQKF', 'Lcqkf@123456']
    nanfeng: ['NFXKF', 'Nfxkf@123456']
    jinxi: ['FZJXXKF', 'Fzjxxkf@123456']
    nancheng: ['FZNCXKF', 'Fzncxkf@123456']
    gaoxin: ['FZSGXKFQKF', 'Fzsgxkf@123456']
    chongren: ['CRXKF', 'Crxkf@123456']
    dongxiang: ['DXQKF', 'Dxqkf@123456']
    zixi: ['ZXXKF', 'Zxxkf@123456']
    lichuan: ['LCXKF', 'Lcxkf@123456']
    donglin: ['FZDLXQKF', 'Fzdlxqkf@123456']
vue:
  project_path: /home/zg/work/gft-item-services
  build_command: npm run dev
  route_dict:
    fuzhou: [ 
      "fztbdcdblb",
      ]
    
compress-package-zg:
  project_path: /home/zg/work/gft-item-services
  build_command: yarn build
  route_dict:
    fuzhou: [ 
      # "gxjychain",
      # "grcychain",
      # "losejobchain",
      # "sy",
      # "zkydchain",
      # "yglychain",
      # "lhjychain",
      # "qyzgtx",
      ]
    lean: ['zkydchaincombine']
    guangchang: []
    yihuang: []
    linchuan: []
    nanfeng: []
    jinxi: []
    nancheng: []
    gaoxin: []
    chongren: []
    dongxiang: []
    zixi: []
    lichuan: []
    donglin: []
  app_dict:
    fuzhou: []
    lean: []
    guangchang: []
    yihuang: []
    linchuan: []
    nanfeng: []
    jinxi: []
    nancheng: []
    gaoxin: []
    chongren: []
    dongxiang: []
    zixi: []
    lichuan: []
    donglin: []
  
